################################################################################
# Individual directory makefile for advent-of-code-2021
################################################################################

# Load the common make rules
include ../makefile
