name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v1
    - name: Install ninja
      run: sudo apt-get install -y ninja-build
    - name: Build
      run: make
    - name: Run tests
      run: make test
      env:
        CTEST_PARALLEL_LEVEL: 2
